Added CI workflows to check versioning in various ways

diff --git a/.github/workflows/pip_install.yml b/.github/workflows/pip_install.yml
--- a/.github/workflows/pip_install.yml
+++ b/.github/workflows/pip_install.yml
@@ -35,14 +35,18 @@ jobs:
 
         - name: Install EESSI test suite with 'pip install'
           run: |
-            ls -al
+            # Make it easier to figure out CI issues in case of CI failures related to SCM versioning
             export SETUPTOOLS_SCM_DEBUG=1
             # install from source distribution tarball, to test release as published on PyPI
             rm -rf dist
+            echo "Running python setup.py sdist"
             python setup.py sdist
             ls dist
 
+            echo "Running python -m pip install --user dist/eessi*.tar.gz"
             python -m pip install --user dist/eessi*.tar.gz
+
+            echo "Checking contents of .local"
             find $HOME/.local
 
             # make sure we are not in the source directory
@@ -51,12 +55,66 @@ jobs:
             python --version
             python -m pip --version
             python -c 'import setuptools; print("setuptools", setuptools.__version__)'
-            # Check if the eessi/testsuite/_version.py file was generated
-            find .local/lib/python${{ matrix.python-version}}/site-packages/eessi/testsuite -name _version.py
-            cat .local/lib/python${{ matrix.python-version}}/site-packages/eessi/testsuite/_version.py
-            testsuite_init=$(python -c 'import eessi.testsuite; print(eessi.testsuite.__file__)')
-            ls -al $(dirname "$testsuite_init")/_version.py
-            python -c 'import eessi.testsuite; print("eessi.testsuite:", eessi.testsuite.__version__)'
 
+            echo "Checking if file 'eessi/testsuite/_version.py' was generated by setuptools_scm":
+            cat .local/lib/python${{ matrix.python-version}}/site-packages/eessi/testsuite/_version.py
+
+            echo "Checking if version can be imported directly from the version file"
+            versionfile_version=$(python -c 'from eessi.testsuite._version import __version__; print(__version__)')
+            echo "Version from version file: $versionfile_version"
+
+            echo "Checking if we can import the __version__ from eessi.testsuite"
+            testsuite_version=$(python -c 'import eessi.testsuite; print("eessi.testsuite:", eessi.testsuite.__version__)')
+            echo "Version imported from eessi.testsuite: $testsuite_version"
+
+            echo "Checking if the version imported from eessi.testsuite matches that from the version file ..."
+            if [[ "$versionfile_version" -ne "$testsuite_version" ]]; then
+                exit 1
+            else
+                echo "... yes!"
+            fi
+
+            echo "Checking if we can import eessi.testsuite.utils"
             python -c 'import eessi.testsuite.utils'
+
+            echo "Checking if we can import eessi.testsuite.tests.apps"
             python -c 'import eessi.testsuite.tests.apps'
+
+            echo "Uninstalling testsuite for next step"
+            python -m pip uninstall -y eessi-testsuite
+
+        - name: Install EESSI test suite with 'pip install git+https'
+          run: |
+            pip install --user "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git@$GITHUB_SHA"
+
+            echo "Checking if file 'eessi/testsuite/_version.py' was generated by setuptools_scm":
+            cat .local/lib/python${{ matrix.python-version}}/site-packages/eessi/testsuite/_version.py
+
+            echo "Checking if version can be imported directly from the version file"
+            githttps_versionfile_version=$(python -c 'from eessi.testsuite._version import __version__; print(__version__)')
+            echo "Version from version file: $githttps_versionfile_version"
+
+            echo "Checking if we can import the __version__ from eessi.testsuite"
+            githttps_testsuite_version=$(python -c 'import eessi.testsuite; print("eessi.testsuite:", eessi.testsuite.__version__)')
+            echo "Version imported from eessi.testsuite: $githttps_testsuite_version"
+
+            echo "Checking if the version imported from eessi.testsuite matches that from the version file ..."
+            if [[ "$githttps_versionfile_version" -ne "$githttps_testsuite_version" ]]; then
+                exit 1
+            else
+                echo "... yes!"
+            fi
+
+            echo "Checking if the version import from a regular pip install and the git+https based install are the same ..."
+            if [[ "$githttps_testsuite_version" -ne "$testsuite_version" ]]; then
+                exit 1
+            else
+                echo "... yes!"
+            fi
+
+            echo "Checking if we can import eessi.testsuite.utils"
+            python -c 'import eessi.testsuite.utils'
+
+            echo "Checking if we can import eessi.testsuite.tests.apps"
+            python -c 'import eessi.testsuite.tests.apps'
+
